version: '3.8'

services:
    app:
        build: .
        container_name: SIDIA
        ports:
            - '8000:8000'
            - '5173:5173'
            - '8080:8080'
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - db
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

    reverb:
        build: .
        command: php artisan reverb:start --debug --host=0.0.0.0 --port=8080
        depends_on:
            - app
        volumes:
            - .:/var/www/html
        restart: unless-stopped

    worker:
        build: .
        command: php artisan queue:listen --verbose --tries=3 --timeout=90
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        restart: unless-stopped

    db:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3307:3306'
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
